module.exports = {
  morgan: require("morgan"),
  helmet: require("helmet"),
  cors: require("cors"),
  express: require("express"),
  compression: require("compression"),
  dotenv: require("dotenv"),
  bodyParser: require("body-parser"),
  responseCodes: require("http-status-codes"),
  sequelize: require("sequelize"),
  axios: require("axios"),
  nodemailer: require("nodemailer"),
  cron: require("node-cron"),
  amqplib: require("amqplib"),
};
